# Optimized for GKE
apiVersion: cosmos.strange.love/v1
kind: CosmosFullNode
metadata:
  # Name should be the chain name and network environment.
  name: cosmoshub-mainnet
spec:
  fullNodeRef: # must be a CosmosFullNode
    namespace: cosmos-operator-system
  replicas: 1
  chain:
    network: mainnet
    chainID: cosmoshub-4
    binary: gaiad
    skipInvariants: true
    genesisURL: "https://snapshots.polkachu.com/genesis/cosmos/genesis.json"
    # Get latest snapshot at: https://www.polkachu.com/tendermint_snapshots/cosmos
    snapshotURL: "https://snapshots.polkachu.com/snapshots/cosmos/cosmos_30655955.tar.lz4"
    # CometBFT config (translates to config.toml)
    config:
      peers: "ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:14956"
    # Cosmos SDK config (translates to app.toml)
    app:
      minGasPrice: "0.0025uatom"
  podTemplate:
    image: "ghcr.io/strangelove-ventures/heighliner/gaia:latest"
    resources:
      requests:
        cpu: "0.5"
      limits:
        cpu: "1"
  volumeClaimTemplate:
    storageClassName: "standard-rwo"
    resources:
      requests:
        storage: 100Gi


